"""Create analytics table

Revision ID: 01f12afdc2e3
Revises: f1be3b17f539
Create Date: 2026-01-02 17:34:27.154719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f12afdc2e3'
down_revision = 'f1be3b17f539'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
