import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import {
  Briefcase,
  Calendar,
  Clock,
  Folder,
  Home,
  Image as ImageIcon,
  LogOut,
  Mail,
} from "lucide-react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen bg-gray-50">
      {/* Sidebar */}
      <aside className="w-20 bg-white border-r border-gray-100 flex flex-col items-center py-6 fixed h-full justify-between">
        <div className="flex flex-col items-center gap-y-8">
          {/* Logo Placeholder */}
          <div className="w-8 h-8 bg-blue-500 rounded-full mb-4"></div>

          {/* Nav Items */}
          <nav className="flex flex-col gap-y-6 text-gray-400">
            <Link href="#" className="text-blue-500 p-2 bg-blue-50 rounded-xl">
              <Home size={20} />
            </Link>
            <Link href="#" className="p-2 hover:bg-gray-50 rounded-xl transition">
              <Mail size={20} />
            </Link>
            <Link href="#" className="p-2 hover:bg-gray-50 rounded-xl transition">
              <ImageIcon size={20} />
            </Link>
            <Link href="#" className="p-2 hover:bg-gray-50 rounded-xl transition">
              <Clock size={20} />
            </Link>
            <Link href="#" className="p-2 hover:bg-gray-50 rounded-xl transition">
              <Folder size={20} />
            </Link>
            <Link href="#" className="p-2 hover:bg-gray-50 rounded-xl transition">
              <Calendar size={20} />
            </Link>
            <Link href="#" className="p-2 hover:bg-gray-50 rounded-xl transition">
              <Briefcase size={20} />
            </Link>
          </nav>
        </div>

        {/* Logout */}
        <button className="text-gray-400 p-2 hover:bg-gray-50 rounded-xl transition">
          <LogOut size={20} />
        </button>
      </aside>

      {/* Main Content Wrapper */}
      <main className="flex-1 ml-20 p-8">{children}</main>
    </div>
  );
}